### ISSUE TITLE
Change redirect to the official CERN website

### ISSUE THREAD

**Issue by porfanid** [CERN/CERN.github.io#1]
I would suggest that the website should redirect to the official CERN website

**Comment by porfanid** [comment]
@duns could you check this?

**Comment by giacomd** [comment]
Thanks for your suggestion @porfanid .
We are in the process of reviewing CERN presence on GH and Open Source in general (with a dedicated programme office), and will decide our official policies in the next few months.
I close this as "won't fix" for now.
Thanks,
Giacomo
